//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbEntitty : DbContext
    {
        public DbEntitty()
            : base("name=DbEntitty")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MCompany> MCompanies { get; set; }
        public virtual DbSet<MCustomer> MCustomers { get; set; }
        public virtual DbSet<MExpens> MExpenses { get; set; }
        public virtual DbSet<MFinancialYear> MFinancialYears { get; set; }
        public virtual DbSet<MMaterial> MMaterials { get; set; }
        public virtual DbSet<MMenu> MMenus { get; set; }
        public virtual DbSet<MOpningBalnce> MOpningBalnces { get; set; }
        public virtual DbSet<MPacking> MPackings { get; set; }
        public virtual DbSet<MPaymentTerm> MPaymentTerms { get; set; }
        public virtual DbSet<MPOTerm> MPOTerms { get; set; }
        public virtual DbSet<MSupplier> MSuppliers { get; set; }
        public virtual DbSet<MUnit> MUnits { get; set; }
        public virtual DbSet<MUser> MUsers { get; set; }
    
        public virtual ObjectResult<SP_Entity_MenuRights_Result> SP_Entity_MenuRights()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Entity_MenuRights_Result>("SP_Entity_MenuRights");
        }
    
        public virtual ObjectResult<Sp_MCompany_EntityReport_Result> Sp_MCompany_EntityReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_MCompany_EntityReport_Result>("Sp_MCompany_EntityReport");
        }
    
        public virtual ObjectResult<Sp_MCustomer_EntityReport_Result> Sp_MCustomer_EntityReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_MCustomer_EntityReport_Result>("Sp_MCustomer_EntityReport");
        }
    
        public virtual ObjectResult<Sp_MExpenses_EntityReport_Result> Sp_MExpenses_EntityReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_MExpenses_EntityReport_Result>("Sp_MExpenses_EntityReport");
        }
    
        public virtual ObjectResult<Sp_MFinancialYear_EntityReport_Result> Sp_MFinancialYear_EntityReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_MFinancialYear_EntityReport_Result>("Sp_MFinancialYear_EntityReport");
        }
    
        public virtual ObjectResult<Sp_MMaterial_EntityReport_Result> Sp_MMaterial_EntityReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_MMaterial_EntityReport_Result>("Sp_MMaterial_EntityReport");
        }
    
        public virtual ObjectResult<Sp_MMenu_EntityReport_Result> Sp_MMenu_EntityReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_MMenu_EntityReport_Result>("Sp_MMenu_EntityReport");
        }
    
        public virtual ObjectResult<Sp_MOpningBalnce_EntityReport_Result> Sp_MOpningBalnce_EntityReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_MOpningBalnce_EntityReport_Result>("Sp_MOpningBalnce_EntityReport");
        }
    
        public virtual ObjectResult<Sp_MPacking_EntityReport_Result> Sp_MPacking_EntityReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_MPacking_EntityReport_Result>("Sp_MPacking_EntityReport");
        }
    
        public virtual ObjectResult<Sp_MPaymentTerms_EntityReport_Result> Sp_MPaymentTerms_EntityReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_MPaymentTerms_EntityReport_Result>("Sp_MPaymentTerms_EntityReport");
        }
    
        public virtual ObjectResult<Sp_MPOTerms_EntityReport_Result> Sp_MPOTerms_EntityReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_MPOTerms_EntityReport_Result>("Sp_MPOTerms_EntityReport");
        }
    
        public virtual ObjectResult<Sp_MSupplier_EntityReport_Result> Sp_MSupplier_EntityReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_MSupplier_EntityReport_Result>("Sp_MSupplier_EntityReport");
        }
    
        public virtual ObjectResult<Sp_MUnit_EntityReport_Result> Sp_MUnit_EntityReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_MUnit_EntityReport_Result>("Sp_MUnit_EntityReport");
        }
    
        public virtual ObjectResult<Sp_MUser_EntityReport_Result> Sp_MUser_EntityReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_MUser_EntityReport_Result>("Sp_MUser_EntityReport");
        }
    }
}
