//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedProductionDataContrax
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCompany
    {
        public long CompanyId { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAdddess { get; set; }
        public string PhoneNo { get; set; }
        public string CellNo { get; set; }
        public string EmailId { get; set; }
        public string PANNo { get; set; }
        public string CST { get; set; }
        public string BST { get; set; }
        public byte[] Logo { get; set; }
        public string AcFlag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Remark { get; set; }
        public string TallyId { get; set; }
    }
}
