//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MExpens
    {
        public long ExpenseId { get; set; }
        public long CompanyId { get; set; }
        public string Module { get; set; }
        public string ExpenseCode { get; set; }
        public string ExpenseName { get; set; }
        public string Specification { get; set; }
        public Nullable<decimal> MaxLimit { get; set; }
        public string AcFlag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Remark { get; set; }
        public string ProductionFlag { get; set; }
        public string BatchExpense { get; set; }
        public string EntryType { get; set; }
    
        public virtual MUser MUser { get; set; }
    }
}
