//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPaymentTerm
    {
        public long PaymentTermId { get; set; }
        public string PaymentTermCode { get; set; }
        public string PaymentTermDescription { get; set; }
        public string Days { get; set; }
        public string AcFlag { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Remarks { get; set; }
        public string EntryType { get; set; }
    }
}
