//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPOTerm
    {
        public long POtermsId { get; set; }
        public long CompanyId { get; set; }
        public string Module { get; set; }
        public string POtermsCode { get; set; }
        public string POtermsName { get; set; }
        public string Description { get; set; }
        public string AcFlag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Remark { get; set; }
        public string EntryType { get; set; }
    
        public virtual MUser MUser { get; set; }
    }
}
